### ISSUE TITLE
Build fails because of libgfortran missing at Travis hosts

### ISSUE THREAD

**Issue by rizar** [mila-udem/blocks#836]
See e.g. https://travis-ci.org/mila-udem/blocks/jobs/80824056, error message is below. I will try to contact Travis support.

```
Message: trial mode expires in 30 days

Traceback (most recent call last):

  File "/home/travis/miniconda/bin/fuel-convert", line 9, in <module>

    load_entry_point('fuel==0.0.1', 'console_scripts', 'fuel-convert')()

  File "/home/travis/miniconda/lib/python2.7/site-packages/setuptools-18.1-py2.7.egg/pkg_resources/__init__.py", line 558, in load_entry_point

  File "/home/travis/miniconda/lib/python2.7/site-packages/setuptools-18.1-py2.7.egg/pkg_resources/__init__.py", line 2682, in load_entry_point

  File "/home/travis/miniconda/lib/python2.7/site-packages/setuptools-18.1-py2.7.egg/pkg_resources/__init__.py", line 2355, in load

  File "/home/travis/miniconda/lib/python2.7/site-packages/setuptools-18.1-py2.7.egg/pkg_resources/__init__.py", line 2361, in resolve

  File "/home/travis/miniconda/lib/python2.7/site-packages/fuel/bin/fuel_convert.py", line 11, in <module>

    from fuel import converters

  File "/home/travis/miniconda/lib/python2.7/site-packages/fuel/converters/__init__.py", line 15, in <module>

    from fuel.converters import caltech101_silhouettes

  File "/home/travis/miniconda/lib/python2.7/site-packages/fuel/converters/caltech101_silhouettes.py", line 4, in <module>

    from scipy.io import loadmat

  File "/home/travis/miniconda/lib/python2.7/site-packages/scipy/io/__init__.py", line 85, in <module>

    from .matlab import loadmat, savemat, whosmat, byteordercodes

  File "/home/travis/miniconda/lib/python2.7/site-packages/scipy/io/matlab/__init__.py", line 13, in <module>

    from .mio import loadmat, savemat, whosmat

  File "/home/travis/miniconda/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 12, in <module>

    from .miobase import get_matfile_version, docfiller

  File "/home/travis/miniconda/lib/python2.7/site-packages/scipy/io/matlab/miobase.py", line 22, in <module>

    from scipy.misc import doccer

  File "/home/travis/miniconda/lib/python2.7/site-packages/scipy/misc/__init__.py", line 49, in <module>

    from scipy.special import comb, factorial, factorial2, factorialk

  File "/home/travis/miniconda/lib/python2.7/site-packages/scipy/special/__init__.py", line 601, in <module>

    from ._ufuncs import *

ImportError: libgfortran.so.1: cannot open shared object file: No such file or directory
```

**Comment by dwf** [comment]
Um, are we installing SciPy with conda? This should never happen...

**Comment by rizar** [comment]
Found an issue at Travis issue tracker: https://github.com/travis-ci/travis-ci/issues/4816

@dwf , can I ask why this should never happen?

**Comment by bartvm** [comment]
https://github.com/conda/conda/issues/444

Looks like this was fixed in Conda 3 days ago? (See NumPy timestamps at https://repo.continuum.io/pkgs/free/linux-64/)

**Comment by vdumoulin** [comment]
@bartvm we're still experiencing these issues in Fuel (see [here](https://travis-ci.org/mila-udem/fuel/jobs/81424394)) on a build that started 10 minutes ago.

**Comment by bartvm** [comment]
So the error was caused by the NumPy Conda package not having libgfortran listed in its requirements. Looking at the package files (https://anaconda.org/anaconda/scipy/files?version=0.16.0&page=2) it seems that SciPy 0.15.1 is also missing it, but 0.16 seems to have it, so there's a good chance the error will disappear if you update Fuel's requirements files (it needs an update anyway: https://requires.io/github/mila-udem/fuel/requirements/?branch=master).

**Comment by bartvm** [comment]
Actually, it seems that although `np19py27_1` has it listed as a requirement, `np19py27_p1` (the MKL version) doesn't. So upgrading to SciPy 0.16 alone isn't enough, you'd have to temporarily disable MKL as well :/

**Comment by bartvm** [comment]
So `sudo apt-get install gfortran` doesn't work on Travis's container infrastructure, but try adding this to the `.travis.yml` file:

```yaml
addons:
  apt:
    packages:
    - gfortran
```
